### ISSUE TITLE
[vg6d_transform] calcolo umidità massima e minima istantanea da umidità relativa istantanea per dati previsti

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#42]
cugino stretto di #8 (del quale incidentalmente confermo chiusura)

la situazione è più o meno simile, con a monte la creazione del grib di umidità relativa sempre via libsim:
`$ vg6d_transform --output-variable-list=B13003 prou.grib urel.grib`

senonché:
```
$ vg6d_transform --comp-stat-proc=254:2 --comp-step='1 00' urel.grib umax.grib
[stderr] ERROR    _default - timerange_v7d_to_g1: GRIB2 statisticalprocessing 2 cannot be converted to GRIB1.
```
allego grib e e log con `LOG4C_PRIORITY` settato a debug (spoiler alert: non dice molto di più)

[urel.zip](https://github.com/ARPA-SIMC/libsim/files/1482255/urel.zip)

**Comment by dcesari** [comment]
Rispondo in inglese così resta a futura memoria quando conquisteremo il mondo.

Unlike tmax & tmin this does not work because grib1 has not statistical processing max & min but only ad-hoc parameters for tmax and tmin variables, which are managed with some magic in libsim. there is however a good chance that this can work with output in grib2, even starting from a grib1 and using the stock templates provided by grib_api:
```
vg6d_transform --comp-stat-proc=254:2 --comp-step='1 00' urel.grib \
  grib_api:/usr/share/grib_api/samples/rotated_ll_sfc_grib2.tmpl:umax.grib
```
